### ISSUE TITLE
bug(api): assistant metadata update overrides model

### ISSUE THREAD

**Issue by andrewrisse** [defenseunicorns/leapfrogai#1156]
### Environment
leapfrog-demo, leapfrogai-api-container

### Steps to reproduce
1. Create an assistant with model set to vllm
2. Update the assistant's metadata only
ex.
```
await openai.beta.assistants.update(createdAssistant.id, {
          metadata: {
            ...(createdAssistant.metadata ? createdAssistant.metadata : undefined),
            avatar: getAssistantAvatarUrl(filePath)
          }
        })
```
3. The returned updated assistant has its model overridden to llama-cpp-python

4. When you then try to use that assistant, the backend throws this error:
```405: Model llama-cpp-python not found. Currently supported models are ['text-embeddings', 'whisper', 'vllm']```

### Expected result

- Model remains vllm

### Actual Result

- Model is set to llama-cpp-python

**Comment by gphorvath** [comment]
This is probably caused by the default in the pydantic type. Modify inherits from Create and the default for Create is `llama-cpp-python`. We just need to loosen this up a bit.

https://github.com/defenseunicorns/leapfrogai/blob/a0d9bc0e901309d1387b5909872b67caf086fdce/src/leapfrogai_api/typedef/assistants/assistant_types.py#L33
